### ISSUE TITLE
error-reporting: Publish nodereport on SIGTERM

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-error-reporting#10]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2299

<a href="/DominicKramer"><img src="https://avatars2.githubusercontent.com/u/14253877?s=88&v=4" height=44 width=44 align=left></a><a href="/DominicKramer">@&shy;DominicKramer</a><br>May 11, 2017 10:43 PM

[nodereport](https://github.com/nodejs/nodereport) is a great package for getting crucial diagnostic info from a node process. We should publish that information to ER on SIGTERM so users get better visibility into the state of the process when the instance crashes (other than when the app itself is crashing).

This issue has been migrated from the cloud-errors-nodejs issue [#83](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/issues/83).

**Comment by DominicKramer** [comment]
It looks like supporting this feature would take considerable changes to the error-reporting UI.  Thus, because there hasn't been requests to add this functionality, I am going to close this issue for now.

Further, because of the format of the data created by the `node-report`, it looks like it would be easiest to use the `node-report` tool directly in conjunction with the Google Cloud Logging library to record crash information in the logs for later analysis.

If there is a need for this functionality in the future, we can further investigate this issue then.
