### ISSUE TITLE
firebase-adminsdk service account: Encountered an error while attempting to transmit an error to the Stackdriver Error Reporting API. ApiError: User not authorized.

### ISSUE THREAD

**Issue by derrickrc** [googleapis/nodejs-error-reporting#542]
I am currently testing via local development using Functions Framework (https://cloud.google.com/functions/docs/running/calling) and am trying to use my **firebase-adminsdk** service account.

I am able to use `gcloud logging write` via gcloud command line to successfully get the manual errors to show up in Stackdriver Error Reporting. 

Here is my setup: 

```
const {ErrorReporting} = require('@google-cloud/error-reporting');

const errors = new ErrorReporting({
        projectId: 'MY PROJECT ID',
        keyFilename: 'MY FIREBASE ADMIN KEY FILE NAME.json', 
        credentials: require('/Users/username/my app/MY FIREBASE ADMIN KEY FILE NAME.json'),
        reportMode: 'always'         
      });
    errors.report('error!'); // try to write an error 

```

When I look in the Cloud Console, I am seeing that the Error Reporting API is enabled for my project and that the firebase-admin service account shows up under **Credentials compatible with this API**. 

When I switch the credentials to my default App Engine service account, it does work. 

This isn't urgent as in the end when I ultimately deployed, I was able to do so without credentials and everything seems to be working, but in my local testing I was confused why this wasn't working with my firebase-adminsdk service account / credentials. Thank you.

**Comment by nicoleczhu** [comment]
In IAM and Admin, does your firebase service account have a role that includes one of [these roles](https://cloud.google.com/error-reporting/docs/iam) required for error reporting?

**Comment by derrickrc** [comment]
Thank you @nicoleczhu. Not sure if I am in the right area, but this is what I see for my firebase-admin service account:

![Screen Shot 2021-02-12 at 1 42 07 PM](https://user-images.githubusercontent.com/46724607/107825575-30d82580-6d38-11eb-85ff-3159eaccd306.png)

And for the default service account: 

![Screen Shot 2021-02-12 at 1 42 10 PM](https://user-images.githubusercontent.com/46724607/107825595-36ce0680-6d38-11eb-97ad-5d1dd08b408f.png)

Does Editor mean that by default it does have the Error Reporting role?

**Comment by nicoleczhu** [comment]
`firebase-adminsdk` and `app engine default` are 2 different accounts. You seem to be using firebase credentials locally, and app engine when deploying. So to get things working locally, you'll still need to add the role(s) to `firebase-adminsdk`, or better yet, create a new "local-development" service account with the right roles. 

The reason it worked when you deployed without credentials is because you're deploying to App Engine. And App Engine already has the `editor` role, which can do all the error reporting stuff. 

Also, locally, you dont need to set credentials in your code. In your local terminal, just run `export GOOGLE_APPLICATION_CREDENTIALS=... path–to_your_file`. 

If you're interested to read more about what's happening, see [authenticating with service accounts](https://cloud.google.com/docs/authentication/production#automatically).
