### ISSUE TITLE
Error reporting fails to include async stack traces

### ISSUE THREAD

**Issue by moberemk** [googleapis/nodejs-error-reporting#67]
Currently when passing errors to Stackdriver our error logs don't include a full stack trace as we use async/await pretty heavily in our system. This is partly a core issue with how Node handles async errors (see https://github.com/nodejs/node/issues/11865 for details and a discussion on that) but it does hamper the utility of this library; even if this isn't something that can be resolved in this specific library having some guidance on how to improve async stack traces in the README would be nice.

#### Environment details

  - OS: Node Alpine container distribution
  - Node.js version: 9.4
  - npm version: 5.6.0
  - @google-cloud/error-reporting version: 0.1.3 (would update to the latest version but there's no obvious changelog anywhere and that makes me nervous without further exploration of the actual commit history)

#### Steps to reproduce

  1. Create two async functions
  2. Call one function from the other
  3. Throw an error in the called function
  4. Catch that error and log it using this library; alternatively, examine the stack trace in a non-debugger context

**Comment by DominicKramer** [comment]
Thanks for the feedback.  Yes, having full stack traces relates to context propagation that lies outside of the scope of this library and impacts Node.js in general.

However, I agree that having a description of this issue and possible solutions would be good to add to the readme.

I would suggest trying the [longjohn](https://www.npmjs.com/package/longjohn) module (in conjunction with this library) that can provide long stack traces.  If you are still having issues, please let me know.

Thanks

**Comment by moberemk** [comment]
I was thinking of giving that a shot once I had a chance to look through it, yeah; if it seems to work as expected should I update this thread, or maybe send a PR updating the README with a note to this effect?

**Comment by DominicKramer** [comment]
You should update this thread so that others can find the solution.  A PR would be great too, but not necessary.  I can update the README for you.

**Comment by DominicKramer** [comment]
When `longjohn` is used, a line containing only dashes is printed in long stack traces when an async hop occurs.  This causes the long stack traces to not appear in the Error Reporting Console since a line with only dashes is not a valid stack trace line.

Next, if `longjohn.empty_frame = ''` or `longjohn.empty_frame = undefined` is used to configure `longjohn`, then an empty line is printed in the stack trace for async hops.  This also causes the Error Reporting Console to not report the long stack trace since a blank line is not a valid stack trace line.

I think the best option is to update the error reporting library to sanitize stack traces, if possible, before sending them to the Error Reporting Console.

I think this is the approach to take, because in talking with the maintainers of the Error Reporting API, a change to determine invalid stack trace lines is not something they API maintainers would want to implement themselves because it is too language specific.

**Comment by ofrobots** [comment]
I'm not sure if automatically sanitizing long stack traces is a good idea. This would be based on pattern matching doesn't generalize to other mechanisms to get async stack traces.

My vote is for documentation in the README.

**Comment by kimroen** [comment]
> I'm not sure if automatically sanitizing long stack traces is a good idea. This would be based on pattern matching doesn't generalize to other mechanisms to get async stack traces.
> 
> My vote is for documentation in the README.

While I appreciate the documentation in the README for this issue, it's not very actionable. At least in the context of a Firebase Cloud Function where errors are sent to StackDriver automatically, catching errors manually, stripping the async jump indicators and then re-throwing (or logging with `console.error`) everywhere isn't practical.

Maybe the `@google-cloud/error-reporting` library (or the `firebase-functions` library?) could include some kind of hook to allow developers to modify the error instance before sending it? By default nothing is done, but the developer can implement the function to strip their async indicators.

> Next, if `longjohn.empty_frame = ''` or `longjohn.empty_frame = undefined` is used to configure `longjohn`, then an empty line is printed in the stack trace for async hops. This also causes the Error Reporting Console to not report the long stack trace since a blank line is not a valid stack trace line.

👆 Also, this would be very useful information to include in the README section, as this was the first thing I tried to handle this in our case.
