### ISSUE TITLE
error-reporting:  Investigate Supporting Express 5

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-error-reporting#7]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2294

<a href="/DominicKramer"><img src="https://avatars2.githubusercontent.com/u/14253877?s=88&v=4" height=44 width=44 align=left></a><a href="/DominicKramer">@&shy;DominicKramer</a><br>May 11, 2017 9:36 PM

The cloud-errors-nodejs repository has PR [#98](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/98) that already contains some preliminary work.

**Comment by DominicKramer** [comment]
Since Express 5 is still in the alpha release stage, does not have a scheduled release date, and there hasn't been feedback asking for Express 5 support in the error reporting library, I am going to close this for now.

When Express 5 has a release date, the final API has stabilized, or there are requests to add support for Express 5, we can re-evaluate adding this feature.
